apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: staging-sample-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-api
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
