# This is a basic workflow to help you get started with Actions

name: Push and Deploy

# Controls when the action will run. 
on: workflow_dispatch

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CLUSTER_NAME: dev
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     - name: Check Out Repo 
       uses: actions/checkout@v2
       
     - run: echo "Building ECR with Cache"
       
     - name: Build and Push to ECR
       uses: whoan/docker-build-with-cache-action@v5
       with:
        registry: xxx.dkr.ecr.eu-central-1.amazonaws.com
        username: ${{ secrets.AWS_ACCESS_KEY_ID }}
        password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        image_name: sample-api
        image_tag: latest
        
     - uses: azure/setup-kubectl@v2.0
       with:
        version: 'v1.23.6'
       id: install
        
     - run: echo "Refreshing replicas"
     
     - run: |
          aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
          aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
          aws configure set default.region eu-central-1
          aws eks update-kubeconfig --name dev --region eu-central-1
          kubectl scale deployment sample-api --replicas=0
          sleep 2s
          kubectl scale deployment sample-api --replicas=1
